export const CITIES = [
  'Berlin',
  'Hamburg',
  'München',
  'Köln',
  'Frankfurt am Main',
  'Stuttgart',
  'Düsseldorf',
  'Dortmund',
  'Essen',
  'Leipzig',
  'Bremen',
  'Dresden',
  'Hannover',
  'Nürnberg',
  'Duisburg',
  'Bochum',
  'Wuppertal',
  'Bielefeld',
  'Bonn',
  'Münster',
  'Karlsruhe',
  'Mannheim',
  'Augsburg',
  'Wiesbaden',
  'Gelsenkirchen',
  'Mönchengladbach',
  'Braunschweig',
  'Kiel',
  'Chemnitz',
  'Aachen',
  'Halle (Saale)',
  'Magdeburg',
  'Freiburg im Breisgau',
  'Krefeld',
  'Lübeck',
  'Oberhausen',
  'Erfurt',
  'Mainz',
  'Rostock',
  'Kassel',
  'Hagen',
  'Saarbrücken',
  'Hamm',
  'Mülheim an der Ruhr',
  'Ludwigshafen am Rhein',
  'Potsdam',
  'Oldenburg',
  'Osnabrück',
  'Leverkusen',
  'Heidelberg',
  'Darmstadt',
  'Paderborn',
  'Regensburg',
  'Würzburg',
  'Ingolstadt',
  'Heilbronn',
  'Ulm',
  'Wolfsburg',
  'Göttingen',
  'Recklinghausen',
  'Pforzheim',
  'Offenbach am Main',
  'Bottrop',
  'Remscheid',
  'Reutlingen',
  'Koblenz',
  'Bergisch Gladbach',
  'Erlangen',
  'Moers',
  'Trier',
  'Jena',
  'Siegen',
  'Hildesheim',
  'Salzgitter',
  'Cottbus',
  'Kaiserslautern',
  'Gütersloh',
  'Schwerin',
  'Düren',
  'Ratingen',
  'Esslingen am Neckar',
  'Tübingen',
  'Ludwigsburg',
  'Villingen-Schwenningen',
  'Konstanz',
  'Marl',
  'Lünen',
  'Flensburg',
  'Witten',
  'Hanau',
  'Gera',
  'Dessau-Roßlau',
  'Velbert',
  'Neuss',
  'Brandenburg an der Havel',
  'Bamberg',
  'Celle',
  'Landshut',
];