export const STREETS = [
  "Hauptstraße",
  "Bahnhofstraße",
  "Goethestraße",
  "Berliner Allee",
  "Schillerplatz",
  "Mühlenweg",
  "Friedrich-Ebert-Straße",
  "Lindenstraße",
  "Am Markt",
  "Kaiserstraße",
  "Rathausplatz",
  "Lessingstraße",
  "Waldweg",
  "Eichenallee",
  "Bismarckstraße",
  "Parkstraße",
  "Gartenstraße",
  "Schulweg",
  "Rosenweg",
  "Kirchplatz",
  "Jahnstraße",
  "Schloßstraße",
  "Bachstraße",
  "Ahornweg",
  "Lerchenweg",
  "Erlenweg",
  "Mozartstraße",
  "Friedhofstraße",
  "Einsteinstraße",
  "Drosselweg",
  "Schubertstraße",
  "Adlerstraße",
  "Brückenstraße",
  "Heinrich-Heine-Straße",
  "Buchenweg",
  "Industriestraße",
  "Fichtestraße",
  "Königstraße",
  "Hermann-Löns-Straße",
  "Sonnenscheinweg",
  "Kantstraße",
  "Tulpenweg",
  "Eichendorffstraße",
  "Dammstraße",
  "Am Wiesenrand",
  "Schillerstraße",
  "Birkenweg",
  "Römerstraße",
  "Hermannstraße",
  "Max-Planck-Straße",
  "Ludwigstraße",
  "Heideweg",
  "Dahlienweg",
  "Beethovenstraße",
  "Rathausstraße",
  "Weidenweg",
  "Hochstraße",
  "Brunnenweg",
  "Schützenstraße",
  "Grüner Weg",
  "Eduard-Mörike-Straße",
  "Bergstraße",
  "Märchenweg",
  "Uhlandstraße",
  "Dorfstraße",
  "Am Sportplatz",
  "Glockenstraße",
  "Elisabethstraße",
  "Friedensstraße",
  "Fasanenweg",
  "Bergmannstraße",
  "An der Kirche",
  "Hafenstraße",
  "Leipziger Straße",
  "Buchenweg",
  "Röntgenstraße",
  "Gneisenaustraße",
  "Höhenweg",
  "Breslauer Straße",
  "Hermann-Hesse-Straße",
  "Jägerweg",
  "Dürerstraße",
  "Schulstraße",
  "Robert-Koch-Straße",
  "Adenauerplatz",
  "Mörikestraße",
  "Kapellenweg",
  "Ludwigsplatz",
  "Am Waldrand",
  "Havelstraße",
  "Erlenweg",
  "Eichenweg",
  "Kurze Straße",
  "Hölderlinstraße",
  "Rathenaustraße",
  "Im Winkel",
  "Mittelweg",
  "Hans-Sachs-Straße",
  "Zum Weiher",
  "Wilhelmstraße",
];